### ISSUE TITLE
Blob names containing slash (/) are not supported

### ISSUE THREAD

**Issue by meidlinga** [sebagomez/azurestorageexplorer#192]
When I want to view a blob with a name containing one or more slashes, only the part in front of the first slash is displayed and treated as directory. Descending into the directory does not show any files or further subdirectories.

**Comment by sebagomez** [comment]
Can you give me an example @meidlinga ?
I've tried and I see every part on the filename as a folder, which is what's expected

![image](https://github.com/user-attachments/assets/66d7e8a3-f0ca-49e7-b63d-cc979927ae05)

**Comment by andres-pipicello** [comment]
Hi, I am having the same issue, in my case using the docker distribution. Here is an example `compose.yaml` file:

```yaml
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    platform: linux/amd64
    hostname: azurite

  azurite-init:
    image: mcr.microsoft.com/azure-cli
    platform: linux/amd64
    environment:
      AZURE_STORAGE_CONNECTION_STRING: 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;'
    depends_on:
      - azurite
    command:
      - bash
      - -c 
      - az storage container create --name container; echo "hello world" | az storage blob upload --container-name container --file /dev/stdin --name parent/child.txt

  azure-storage-explorer:
    image: sebagomez/azurestorageexplorer
    platform: linux/amd64
    environment:
      AZURE_STORAGE_CONNECTIONSTRING: 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;'
    ports:
      - "8181:8080"
    depends_on:
      - azurite

```

This is the result when browsing http://localhost:8181:

`parent` shows:
![image](https://github.com/user-attachments/assets/8503ea8c-8e3a-415f-8d95-fabfa89ce890)
but child does not:
![image](https://github.com/user-attachments/assets/0774b877-13a4-459a-b8df-dd7599c1154d)

Regards
